const fs = require('fs');

const seedFile = '/home/vaiunix_111/College/OptiFlow/2_Optiflow/back-end/prisma/seed.ts';
let content = fs.readFileSync(seedFile, 'utf8');

const injectionPoint = 'console.log("\\n==========================================================");';

const massiveBlock = `
  // =====================================================================
  // MASSIVE MOCK DATA GENERATION BLOCK FOR DEMO
  // =====================================================================
  console.log("Generating massive mock data for demo dashboards...");

  const teamSales = await prisma.team.create({
    data: { branchId: branch.id, name: "Acme Sales & Operations" }
  });

  const projectQ3 = await prisma.project.create({
    data: { teamId: teamCore.id, name: "Q3 Cloud Migration", status: "Active", startDate: new Date(), endDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000), createdById: userBob.id }
  });
  const projectMobile = await prisma.project.create({
    data: { teamId: teamCore.id, name: "Mobile App V2", status: "Active", startDate: new Date(), endDate: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000), createdById: userBob.id }
  });
  const projectSOC2 = await prisma.project.create({
    data: { teamId: teamSales.id, name: "SOC2 Audit Prep", status: "Active", startDate: new Date(), endDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000), createdById: userRachel.id }
  });
  const projectCRM = await prisma.project.create({
    data: { teamId: teamSales.id, name: "Salesforce CRM Integration", status: "Active", startDate: new Date(), endDate: new Date(Date.now() + 120 * 24 * 60 * 60 * 1000), createdById: userRachel.id }
  });

  const teamMembers = [userDavid, userEmma, userFrank, userGrace, userIan, userJulia, userKevin];
  const demoProjects = [projectQ3, projectMobile, projectSOC2, projectCRM];
  const taskPriorities = [TaskPriority.Low, TaskPriority.Medium, TaskPriority.High, TaskPriority.Urgent];
  
  const createdTasks: any[] = [];
  for (let i = 0; i < 50; i++) {
    let status = TaskStatus.Draft;
    if (i >= 10 && i < 30) status = TaskStatus.Active;
    else if (i >= 30 && i < 40) status = TaskStatus.Completed;
    else if (i >= 40) status = TaskStatus.Blocked;

    const assignedTo = teamMembers[i % teamMembers.length];
    const proj = demoProjects[i % demoProjects.length];
    const estimated = Math.floor(Math.random() * 20) + 2;
    const actual = status === TaskStatus.Completed ? estimated : Math.floor(Math.random() * estimated);

    const t = await prisma.task.create({
      data: {
        companyId: acmeCorp.id,
        projectId: proj.id,
        title: \`Demo Task \${i + 1} - \${proj.name}\`,
        description: \`Autogenerated task for workload simulation.\`,
        status: status,
        priority: taskPriorities[Math.floor(Math.random() * 4)],
        assignedToId: assignedTo.id,
        createdById: userBob.id,
        dueDate: new Date(Date.now() + (Math.random() * 30 - 15) * 24 * 60 * 60 * 1000),
        estimatedHours: estimated,
        actualHours: actual,
        completedAt: status === TaskStatus.Completed ? new Date() : null,
      }
    });
    createdTasks.push(t);
  }

  const blockedTasks = createdTasks.filter(t => t.status === TaskStatus.Blocked);
  for (let i = 0; i < Math.min(5, blockedTasks.length); i++) {
    await prisma.escalation.create({
      data: {
        companyId: acmeCorp.id,
        taskId: blockedTasks[i].id,
        reportedById: blockedTasks[i].assignedToId,
        targetManagerId: userBob.id,
        title: \`Blocked: \${blockedTasks[i].title}\`,
        description: \`Blocked by external dependency. Need PM review.\`,
        status: EscalationStatus.Open
      }
    });
  }

  for (let i = 0; i < 20; i++) {
    await prisma.auditLog.create({
      data: {
        companyId: acmeCorp.id,
        action: i % 2 === 0 ? AuditAction.LOGIN : AuditAction.UPDATE,
        entityType: i % 2 === 0 ? "User" : "Task",
        entityId: i % 2 === 0 ? userDavid.id : createdTasks[0].id,
        performedById: teamMembers[i % teamMembers.length].id,
        ipAddress: "192.168.1." + (100 + i),
        userAgent: "Mozilla/5.0 Demo Browser",
        usedPermissionSlug: i % 2 === 0 ? null : "tasks.manage"
      }
    });
  }

  await prisma.complianceViolation.create({
    data: {
      companyId: acmeCorp.id,
      ruleId: rule2FA.id,
      entityType: "User",
      entityId: userFrank.id,
      status: ViolationStatus.Open,
      severity: Severity.Critical,
      reportedById: userSamuel.id,
      resolutionRemarks: "Frank has not setup 2FA yet."
    }
  });

  const violationUnderReview = await prisma.complianceViolation.create({
    data: {
      companyId: acmeCorp.id,
      ruleId: rule2FA.id, // Reused a safe rule since ruleGDPR might not exist depending on the state
      entityType: "Project",
      entityId: projectQ3.id,
      status: ViolationStatus.Under_Review,
      severity: Severity.High,
      reportedById: userSamuel.id,
      resolutionRemarks: "Pending review of newly submitted data masking script."
    }
  });

  await prisma.complianceEvidence.create({
    data: {
      companyId: acmeCorp.id,
      userId: userDavid.id,
      violationId: violationUnderReview.id,
      taskId: createdTasks[0].id,
      title: "Data Masking Script Evidence",
      evidenceType: "Code Snippet",
      status: EvidenceStatus.Pending
    }
  });

  await prisma.complianceViolation.create({
    data: {
      companyId: acmeCorp.id,
      ruleId: rule2FA.id,
      entityType: "Project",
      entityId: projectSOC2.id,
      status: ViolationStatus.Resolved,
      severity: Severity.Medium,
      reportedById: userSamuel.id,
      resolutionRemarks: "Approved financial log audit trail."
    }
  });

  await prisma.platformSupportAccess.createMany({
    data: [
      {
        adminUserId: platformAdmin.id,
        companyId: acmeCorp.id,
        reason: "Initial Tenant Setup Check",
        expiresAt: new Date(Date.now() - 24 * 60 * 60 * 1000) 
      },
      {
        adminUserId: platformAdmin.id,
        companyId: acmeCorp.id,
        reason: "Investigating PM Dashboard bug",
        expiresAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000) 
      },
      {
        adminUserId: platformAdmin.id,
        companyId: acmeCorp.id,
        reason: "Routine tenant audit",
        expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000) 
      }
    ]
  });

`;

content = content.replace(injectionPoint, massiveBlock + '\n  ' + injectionPoint);
fs.writeFileSync(seedFile, content, 'utf8');
console.log("Injected massive block into seed.ts");
